version: '3.5'

services:
  redis:
    container_name: redis-cache
    image: redis
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
      - REDIS_DB=projeto
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=true
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
