version: '3.1'

services:
  db:
    build: .
    container_name: jwt-auth
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker -POSTGRES_DB=jwtAuth
  redis:
    container_name: redis-cache
    image: redis
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
      - REDIS_DB=projeto
    ports:
      - "6379:6379"
